### PR TITLE
Add files todo_list project for code review

### PR DESCRIPTION
**Pull request by gak92**
In this pull request, I created the to-do list project for code review practice.

### CODE REVIEW

**Comment by trace-kadenyi** [comment]
Hi [gak92](https://github.com/gak92),
Good job so far!

## Highlights
-  No linters errors 👍
- Project documented professionally 👍
- The output is well-designed and simple to use. 
- Good use of Classes and ES6 imports/exports 👍
## Required Changes ♻️
- I have noticed that you don't use arrow functions as per the ES6 requirements. I would advise you to adopt the use of arrow functions in your projects as it enhances the professionalism of your code. 

```
static editTask(value, index, tasksList) {
    tasksList[index].description = value;
    LocalStorage.saveData(tasksList);
    this.showAllTasks(tasksList);
  }
```
(OPTIONAL) Consider placing your JavaScript files in a modules folder. This would make your code neater and more professional. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Be sure to tag me directly so that I can receive your messages promptly.

**Comment by gak92** [comment]
> Hi [gak92](https://github.com/gak92), Good job so far!
> 
> ## Highlights
> * No linters errors 👍
> * Project documented professionally 👍
> * The output is well-designed and simple to use.
> * Good use of Classes and ES6 imports/exports 👍
> 
> ## Required Changes ♻️
> * I have noticed that you don't use arrow functions as per the ES6 requirements. I would advise you to adopt the use of arrow functions in your projects as it enhances the professionalism of your code.
> 
> ```
> static editTask(value, index, tasksList) {
>     tasksList[index].description = value;
>     LocalStorage.saveData(tasksList);
>     this.showAllTasks(tasksList);
>   }
> ```
> 
> (OPTIONAL) Consider placing your JavaScript files in a modules folder. This would make your code neater and more professional.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Be sure to tag me directly so that I can receive your messages promptly.

Thanks for the feedback.
I will fix that.

**Comment by trace-kadenyi** [comment]
Hi @[gak92](https://github.com/gak92),

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Good design 💯 
- Good PR title and description 💪🏿 
- Proper use of arrow functions 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gak92** [comment]
Thanks for the feedback.
I will merge it.

**Pull request merged**
